### ISSUE TITLE
2 small points

### ISSUE THREAD

**Issue by mtravers** [Quantisan/cascalog-doc#3]
That I needed to figure out to get the demos to run, and should be in the doc to spare others:
- I needed to add 
  :profiles { :dev {:dependencies [[org.apache.hadoop/hadoop-core "0.20.2-dev"]]}}
  to project.clj
- needed to do
  export JAVA_OPTS=-Xmx768m 
  before starting, or got OutOfMemory errors.

**Comment by Quantisan** [comment]
@mtravers thank you for taking the time to pointing these out
