### ISSUE TITLE
one spelling mistake in getting-started page

### ISSUE THREAD

**Issue by jiacai2050** [Quantisan/cascalog-doc#4]
the exact page url is 
http://cascalog.org/articles/getting_started.html#toc_14
…… as well as transposing horizontal to vertical (e.g. defmapcapop), 
in above sentence the last word "defmapcapop" is wrong, As far I know ,there is a "defmapcatop" operator instead of "defmapcapop"

**Comment by Quantisan** [comment]
@summerljc thanks for taking the time to report this
