### ISSUE TITLE
Also set jvm option -Xms768m

### ISSUE THREAD

**Issue by jocrau** [Quantisan/cascalog-doc#7]
It is advised to set jvm option -Xmx768m. This fails in environments, in which the option -Xms is set to a higher value. Both should be set to the same value:

```
:jvm-opts ["-Xms768m" "-Xmx768m"]
```

**Comment by michaelklishin** [comment]
Not necessarily. The upper bound should be greater or equals to the lower one but that's the only requirement.

**Comment by jocrau** [comment]
That's true. But I was referring to the documentation and suggest to change the line to

```
:jvm-opts ["-Xms768m" "-Xmx768m"]
```

The documentation doesn't say "768m or more" either ;-)

**Comment by Quantisan** [comment]
To clarify, I take that this is to prevent user who has an external environment var set for java to Xms > 768m already thus causing the Xmx setting we use in the project.clj to fail?

**Comment by jocrau** [comment]
Yes, that's correct.

**Comment by Quantisan** [comment]
@jocrau thanks for pointing it out
